<?php

namespace Omnipay\Yijipay;

/**
 * Class Gateway
 * @package Omnipay\WechatPay
 */
class Gateway extends BaseAbstractGateway
{
    /**
     * PHP 5 allows developers to declare constructor methods for classes.
     * Classes which have a constructor method call this method on each newly-created object,
     * so it is suitable for any initialization that the object may need before it is used.
     *
     * Note: Parent constructors are not called implicitly if the child class defines a constructor.
     * In order to run a parent constructor, a call to parent::__construct() within the child constructor is required.
     *
     * param [ mixed $args [, $... ]]
     * @return void
     * @link http://php.net/manual/en/language.oop5.decon.php
     */


    public function getName()
    {
        return 'Yijipay';
    }

    public function getVersion()
    {
        return '1.0'; // TODO: Change the autogenerated stub
    }

    public function getSignType()
    {
        return 'MD5'; // TODO: Change the autogenerated stub
    }

    public function getPaymentType()
    {
        return ''; // TODO: Change the autogenerated stub
    }

    public function getMemberType()
    {
        return 'MEMBER_TYPE_PATERN'; // TODO: Change the autogenerated stub
    }

    public function getProtocol()
    {
        return 'httpPost';
    }


}
