<?php
// +----------------------------------------------------------------------
// | When work is a pleasure, life is a joy!
// +----------------------------------------------------------------------
// | Company: YG | User: ShouKun Liu  |  Email:24147287@qq.com  | Time:2017/3/27 16:29
// +----------------------------------------------------------------------
// | TITLE: this to do?
// +----------------------------------------------------------------------


namespace Omnipay\Yijipay;


class PcGateway extends Gateway
{

    public function getUserTerminalType()
    {
        return 'PC';
    }

    public function getService()
    {
        return 'aggregatePay'; // TODO: Change the autogenerated stub
    }

}